// <auto-generated />
namespace One.Test.Mockdata.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createUserAuthonticationTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createUserAuthonticationTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201702022248442_createUserAuthonticationTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
